//==========================================================
// Generated by export_world.lua
//==========================================================

#include "forest.h"

//==========================================================
// Generated by export_world.lua
//==========================================================


/* ---------- Destination Rectangles ----------*/

static const xRectangle largeTrees[] =
{
    { .x = 225, .y = 0, .width = 31, .height = 41 },
    { .x = 210, .y = 0, .width = 41, .height = 41 },
    { .x = 224, .y = 31, .width = 32, .height = 63 },
    { .x = 224, .y = 55, .width = 32, .height = 63 },
    { .x = 224, .y = 79, .width = 32, .height = 63 },
    { .x = 224, .y = 103, .width = 32, .height = 63 },
    { .x = 224, .y = 127, .width = 32, .height = 63 },
    { .x = 63, .y = 108, .width = 41, .height = 63 },
    { .x = 51, .y = 129, .width = 41, .height = 63 },
    { .x = 83, .y = 129, .width = 41, .height = 63 },
    { .x = 154, .y = 90, .width = 41, .height = 63 },
    { .x = 169, .y = 90, .width = 41, .height = 63 },
};

static const xRectangle treeCuts[] =
{
    { .x = 222, .y = 170, .width = 16, .height = 14 },
};

static const xRectangle ponds[] =
{
    { .x = 80, .y = 64, .width = 96, .height = 80 },
};

static const xRectangle logs[] =
{
    { .x = 199, .y = 21, .width = 25, .height = 11 },
};

static const xRectangle mushrooms[] =
{
    { .x = 148, .y = 149, .width = 8, .height = 8 },
    { .x = 164, .y = 149, .width = 8, .height = 8 },
    { .x = 76, .y = 31, .width = 8, .height = 8 },
    { .x = 60, .y = 31, .width = 8, .height = 8 },
    { .x = 44, .y = 31, .width = 8, .height = 8 },
    { .x = 211, .y = 8, .width = 8, .height = 8 },
};

static const xRectangle rocksSmall[] =
{
    { .x = 178, .y = 85, .width = 10, .height = 7 },
};

static const xRectangle smallTrees[] =
{
    { .x = 28, .y = 0, .width = 23, .height = 32 },
    { .x = 44, .y = 0, .width = 23, .height = 32 },
    { .x = 60, .y = 0, .width = 23, .height = 32 },
    { .x = 76, .y = 0, .width = 23, .height = 32 },
    { .x = 28, .y = 16, .width = 23, .height = 32 },
    { .x = 44, .y = 16, .width = 23, .height = 32 },
    { .x = 60, .y = 16, .width = 23, .height = 32 },
    { .x = 76, .y = 16, .width = 23, .height = 32 },
};

static const xRectangle treeStumps[] =
{
    { .x = 21, .y = 36, .width = 7, .height = 8 },
};

static const xRectangle flowerYellow[] =
{
    { .x = 52, .y = 164, .width = 7, .height = 10 },
};


/* ---------- Implementation ----------*/

void xLoadTreesLarge1(World *world)
{
    for (int i=0; i<ARRAY_COUNT(largeTrees); i++)
    {
        xAddTree(world, TREE_LARGE, largeTrees[i]);
    }
}

void xLoadTreesSmall1(World *world)
{
    for (int i=0; i<ARRAY_COUNT(smallTrees); i++)
    {
        xAddTree(world, TREE_SMALL, smallTrees[i]);
    }
}

void xLoadMushrooms(World *world)
{
    for (int i=0; i<ARRAY_COUNT(mushrooms); i++)
    {
        xAddMushroom(world, mushrooms[i]);
    }
}